### ISSUE TITLE
Authorization 

### ISSUE THREAD

**Issue by nest-edu** [QueenKunkun/angular-libs#2]
Good day dear QueenKunkun, I need to send a token to authenticate on the server, Is there an example?

ngOnInit(): void {
    this.sseClient.get('http://localhost:8181/sse',{ headers: {
                    'Authorization': 'Bearer ' + token,
                }})
      .subscribe(data => {
        console.log('got data from EventSource', data);
      });
  }

**Comment by dumasss163** [comment]
@nest-edu I got the same issue, unfortunately, this is a limitation of browser e.g. chrome, which does not support other kinds of headers including `Authorization`.

**Comment by ap-81** [comment]
I need to do a "POST" request, specifically post a file, do some processing and track its progress. Any chance of incorporating a "POST" request to the library ?
